using System.Collections.Generic;

namespace TibiaDataApi.Contracts.Public.Creatures
{
    public sealed record CreatureInfoboxResponse(
        string? Name,
        string? ActualName,
        string? Plural,
        string? Article,
        string? Armor,
        string? Mitigation,
        string? Summon,
        string? Convince,
        string? Illusionable,
        string? IsBoss,
        string? CreatureClass,
        string? PrimaryType,
        string? SecondaryType,
        string? Abilities,
        string? MaxDamage,
        string? Pushable,
        string? PushObjects,
        string? WalksAround,
        string? WalksThrough,
        string? PhysicalDamageModifier,
        string? EarthDamageModifier,
        string? FireDamageModifier,
        string? DeathDamageModifier,
        string? EnergyDamageModifier,
        string? HolyDamageModifier,
        string? IceDamageModifier,
        string? LifeDrainDamageModifier,
        string? DrownDamageModifier,
        string? HealingModifier,
        string? Sounds,
        string? Implemented,
        string? RaceId,
        string? Notes,
        string? Behaviour,
        string? RunsAt,
        string? Speed,
        string? Strategy,
        string? Location,
        string? History,
        string? UsesSpells,
        string? AttackType,
        string? SpawnType,
        string? BestiaryClass,
        string? BestiaryDifficulty,
        string? BestiaryOccurrence,
        string? BosstiaryCategory,
        IReadOnlyDictionary<string, string>? Fields);
}
